# Generated by Django 5.0.3 on 2024-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tshirts'),
        ),
    ]
