# Generated by Django 5.0.3 on 2024-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_tshirt_product_id_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='product_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
