# Generated by Django 5.0.3 on 2024-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_tshirt_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='product_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
